# classification: "Airbus Amber"
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-config
  namespace: a400m-ref-data
  labels:
    classification: Airbus-Amber
spec:
  destination:
    namespace: a400m-ref-data
    server: "https://kubernetes.default.svc"
  project: a400m-ref-data
  source:
    path: "namespace-config"
    repoURL: "https://github.com/dpsancha/argo-example"
    targetRevision: HEAD