apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}-backend
    app.kubernetes.io/instance: {{ .Values.appName }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: tcp-web
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}-backend
    app.kubernetes.io/instance: {{ .Values.appName }}
    app.kubernetes.io/component: backend 