kind: ServiceAccount
apiVersion: v1
metadata:
  name: spark
  namespace: a400m-ref-data
imagePullSecrets:
  - name: docker
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-role
  namespace: a400m-ref-data
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - persistentvolumeclaims
      - events
      - configmaps
    verbs:
      - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-role-binding
  namespace: a400m-ref-data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: a400m-ref-data-ops
  - kind: ServiceAccount
    name: spark
    namespace: a400m-ref-data
